### PR TITLE
Issue #142: [iOS] Incorrect MIME Types

### LINKED ISSUE #142: iOS 10 - Many files served from Library have lost MIME Type
After upgrading to iOS 10 all my svg images are no longer drawing. On closer inspection, their MIME Type has changed to `application/octet-stream`. (It was `image/svg+xml` under iOS 9.3.) In fact all files apart from index.html have the same issue, but it seems the webView is able to make sense of them despite the mismatch.

screen shot 2016-09-22 at 17 11 57

### PR DESCRIPTION
**Pull request by jcf120**
Fixes #142 

Most files served from ContentSync's 'localPath' had a MIME Type of `application/octet-stream` under iOS 10. Surprisingly the only problematic effect I've seen from this so far is that svg graphics weren't drawing.

Also the anti-caching headers weren't being set if the existing `Accept` header was missing.

### CODE REVIEW

File: src/ios/ContentSync.m [hunk 1]
```diff
@@ -610,13 +611,20 @@ + (NSURLRequest*)canonicalRequestForRequest:(NSURLRequest*)theRequest {
 - (void)startLoading {
     NSData *data = [NSData dataWithContentsOfFile:self.request.URL.path];
 
-    // add the no-cache HEADERs to the request while preserving the existing HEADER values.
-    NSDictionary *headers = [NSDictionary dictionaryWithObjectsAndKeys:
-                             [self.request.allHTTPHeaderFields objectForKey:@"Accept"], @"Accept",
```
Comment (jcf120) [inline src/ios/ContentSync.m]: Was there a reason for only preserving the `Accept` field, rather than the the whole header?

**Comment by DhiaNHM** [comment]
just confirming this fix worked for our broken SVG's on IOS10, any ETA on this being pulled into a release?

File: src/ios/ContentSync.m (hunk 1 above)
Comment (timkim) [inline src/ios/ContentSync.m]: Not sure what the original reasoning was. Might've been an oversight.

**Comment by timkim** [comment]
Hi @DhiaNHM 

I've merged this in, but if you're using the PhoneGap Developer App expect to see a release sometime this week.
